const MC_ASSET_BASE = 'https://assets.mcasset.cloud/1.21.11/assets/minecraft/textures/block/';
const BLOCKS = [
  { name:'Stone', file:'stone.png', pal:['#7a7a7a'] },
  { name:'Cobblestone', file:'cobblestone.png', pal:['#6f6f6f'] },
  { name:'Smooth Stone', file:'smooth_stone.png', pal:['#8b8b8b'] },
  { name:'Stone Bricks', file:'stone_bricks.png', pal:['#7b7b7b'] },
  { name:'Mossy Stone Bricks', file:'mossy_stone_bricks.png', pal:['#60724f'] },
  { name:'Deepslate', file:'deepslate.png', pal:['#505056'] },
  { name:'Cobbled Deepslate', file:'cobbled_deepslate.png', pal:['#4a4a52'] },
  { name:'Blackstone', file:'blackstone.png', pal:['#242329'] },
  { name:'Basalt', file:'basalt_top.png', pal:['#4a4644'] },
  { name:'Tuff', file:'tuff.png', pal:['#6f736b'] },
  { name:'Dirt', file:'dirt.png', pal:['#8a5a37'] },
  { name:'Grass Block', file:'grass_block_top.png', pal:['#5f9f3f'] },
  { name:'Podzol', file:'podzol_top.png', pal:['#7b5930'] },
  { name:'Mycelium', file:'mycelium_top.png', pal:['#6e6077'] },
  { name:'Sand', file:'sand.png', pal:['#d8c17a'] },
  { name:'Red Sand', file:'red_sand.png', pal:['#b85f2c'] },
  { name:'Gravel', file:'gravel.png', pal:['#87827c'] },
  { name:'Clay', file:'clay.png', pal:['#9aa3a8'] },
  { name:'Snow', file:'snow.png', pal:['#f0fbff'] },
  { name:'Ice', file:'ice.png', pal:['#9fd5f2'] },
  { name:'Oak Planks', file:'oak_planks.png', pal:['#b6823c'] },
  { name:'Spruce Planks', file:'spruce_planks.png', pal:['#806037'] },
  { name:'Birch Planks', file:'birch_planks.png', pal:['#c9b06b'] },
  { name:'Jungle Planks', file:'jungle_planks.png', pal:['#b46d4c'] },
  { name:'Acacia Planks', file:'acacia_planks.png', pal:['#b75f35'] },
  { name:'Dark Oak Planks', file:'dark_oak_planks.png', pal:['#53381e'] },
  { name:'Mangrove Planks', file:'mangrove_planks.png', pal:['#7f3430'] },
  { name:'Cherry Planks', file:'cherry_planks.png', pal:['#e5a0a4'] },
  { name:'Bamboo Planks', file:'bamboo_planks.png', pal:['#c8b451'] },
  { name:'Crimson Planks', file:'crimson_planks.png', pal:['#71354d'] },
  { name:'Oak Log', file:'oak_log_top.png', pal:['#9a6b34'] },
  { name:'Spruce Log', file:'spruce_log_top.png', pal:['#6b4d2b'] },
  { name:'Birch Log', file:'birch_log_top.png', pal:['#c9b987'] },
  { name:'Jungle Log', file:'jungle_log_top.png', pal:['#8d6739'] },
  { name:'Acacia Log', file:'acacia_log_top.png', pal:['#9b5731'] },
  { name:'Dark Oak Log', file:'dark_oak_log_top.png', pal:['#4b3320'] },
  { name:'Mangrove Log', file:'mangrove_log_top.png', pal:['#6b2724'] },
  { name:'Cherry Log', file:'cherry_log_top.png', pal:['#d88d97'] },
  { name:'Bamboo Block', file:'bamboo_block_top.png', pal:['#b99e3f'] },
  { name:'Stripped Oak Log', file:'stripped_oak_log_top.png', pal:['#b7894a'] },
  { name:'Bricks', file:'bricks.png', pal:['#a84832'] },
  { name:'Mud Bricks', file:'mud_bricks.png', pal:['#8a6655'] },
  { name:'Prismarine', file:'prismarine.png', pal:['#5a9a91'] },
  { name:'Dark Prismarine', file:'dark_prismarine.png', pal:['#335b57'] },
  { name:'Sea Lantern', file:'sea_lantern.png', pal:['#bfe5d8'] },
  { name:'Quartz Block', file:'quartz_block_top.png', pal:['#e8e1d2'] },
  { name:'Purpur Block', file:'purpur_block.png', pal:['#a878a8'] },
  { name:'End Stone', file:'end_stone.png', pal:['#d7d29a'] },
  { name:'End Stone Bricks', file:'end_stone_bricks.png', pal:['#c4c081'] },
  { name:'Nether Bricks', file:'nether_bricks.png', pal:['#31181d'] },
  { name:'Netherrack', file:'netherrack.png', pal:['#7b2828'] },
  { name:'Soul Sand', file:'soul_sand.png', pal:['#554036'] },
  { name:'Soul Soil', file:'soul_soil.png', pal:['#4a352c'] },
  { name:'Glowstone', file:'glowstone.png', pal:['#d7a83d'] },
  { name:'Obsidian', file:'obsidian.png', pal:['#201426'] },
  { name:'Crying Obsidian', file:'crying_obsidian.png', pal:['#2a1837'] },
  { name:'Magma Block', file:'magma.png', pal:['#aa471f'] },
  { name:'Warpped Nylium', file:'warped_nylium.png', pal:['#2d7d72'] },
  { name:'Crimson Nylium', file:'crimson_nylium.png', pal:['#7d2537'] },
  { name:'Shroomlight', file:'shroomlight.png', pal:['#e58b4d'] },
  { name:'Coal Ore', file:'coal_ore.png', pal:['#666666'] },
  { name:'Iron Ore', file:'iron_ore.png', pal:['#8d7f73'] },
  { name:'Copper Ore', file:'copper_ore.png', pal:['#947969'] },
  { name:'Gold Ore', file:'gold_ore.png', pal:['#9b844a'] },
  { name:'Redstone Ore', file:'redstone_ore.png', pal:['#7b4847'] },
  { name:'Lapis Ore', file:'lapis_ore.png', pal:['#52619b'] },
  { name:'Diamond Ore', file:'diamond_ore.png', pal:['#6f9fa2'] },
  { name:'Emerald Ore', file:'emerald_ore.png', pal:['#5a9a6a'] },
  { name:'Amethyst Block', file:'amethyst_block.png', pal:['#8567bd'] },
  { name:'Ancient Debris', file:'ancient_debris_top.png', pal:['#5d4038'] },
  { name:'Coal Block', file:'coal_block.png', pal:['#151515'] },
  { name:'Iron Block', file:'iron_block.png', pal:['#d0d0d0'] },
  { name:'Copper Block', file:'copper_block.png', pal:['#c87f55'] },
  { name:'Gold Block', file:'gold_block.png', pal:['#f4cb38'] },
  { name:'Redstone Block', file:'redstone_block.png', pal:['#b8201d'] },
  { name:'Lapis Block', file:'lapis_block.png', pal:['#2146a9'] },
  { name:'Diamond Block', file:'diamond_block.png', pal:['#5cc8c8'] },
  { name:'Emerald Block', file:'emerald_block.png', pal:['#2cb556'] },
  { name:'Netherite Block', file:'netherite_block.png', pal:['#443e43'] },
  { name:'Honeycomb Block', file:'honeycomb_block.png', pal:['#e29a24'] },
  { name:'White Wool', file:'white_wool.png', pal:['#e8e8e8'] },
  { name:'Orange Wool', file:'orange_wool.png', pal:['#e88624'] },
  { name:'Magenta Wool', file:'magenta_wool.png', pal:['#bd44b8'] },
  { name:'Light Blue Wool', file:'light_blue_wool.png', pal:['#5da8d6'] },
  { name:'Yellow Wool', file:'yellow_wool.png', pal:['#d8c52a'] },
  { name:'Lime Wool', file:'lime_wool.png', pal:['#7bbb25'] },
  { name:'Pink Wool', file:'pink_wool.png', pal:['#e37aa2'] },
  { name:'Gray Wool', file:'gray_wool.png', pal:['#444444'] },
  { name:'Cyan Wool', file:'cyan_wool.png', pal:['#158991'] },
  { name:'Purple Wool', file:'purple_wool.png', pal:['#7b2bb3'] },
  { name:'Blue Wool', file:'blue_wool.png', pal:['#2a43a8'] },
  { name:'Brown Wool', file:'brown_wool.png', pal:['#68411d'] },
  { name:'Green Wool', file:'green_wool.png', pal:['#4c7a23'] },
  { name:'Red Wool', file:'red_wool.png', pal:['#9f2525'] },
  { name:'Black Wool', file:'black_wool.png', pal:['#151519'] }
];

function makeFallbackCanvas(color) {
  const oc = document.createElement('canvas');
  oc.width = 16; oc.height = 16;
  const octx = oc.getContext('2d');
  octx.fillStyle = color;
  octx.fillRect(0,0,16,16);
  octx.fillStyle = 'rgba(255,255,255,.12)';
  octx.fillRect(0,0,16,4);
  octx.fillStyle = 'rgba(0,0,0,.18)';
  octx.fillRect(0,12,16,4);
  return oc;
}

const blockCanvases = BLOCKS.map(b => makeFallbackCanvas(b.pal[0]));
